[
  {
    "id": 1,
    "nome": "Vinoperfect Sérum Iluminador",
    "categoria": "seruns",
    "subcategoria": "Séruns",
    "colecao": "Vinoperfect",
    "descricao_curta": "Sérum antimanchas de alta performance com Vinolevure™",
    "descricao_completa": "O sérum iluminador número 1 da Caudalie, alternativa natural à vitamina C. Reduz visivelmente manchas, desuniformidade e ilumina a pele em apenas 28 dias. Fórmula vegana com Vinolevure™, extrato exclusivo da levedura da uva.",
    "imagem": "assets/products/vinoperfect-serum.jpg",
    "imagem_placeholder": "vinoperfect",
    "preco": 349.00,
    "preco_formatado": "R$ 349,00",
    "parcelamento": "em até 6x de R$ 58,17",
    "beneficios": ["Reduz manchas em 28 dias", "Ilumina e unifica o tom", "Alternativa natural à vitamina C", "Fórmula vegana"],
    "ingredientes": "Vinolevure™ (extrato de levedura da uva), Niacinamida, Ácido Hialurônico, Vitamina E",
    "volume": "30ml",
    "modo_uso": "Aplique algumas gotas pela manhã sobre a pele limpa, antes do hidratante. Use filtro solar durante o dia.",
    "tags": ["antimanchas", "iluminador", "sérum", "vinoperfect", "bestseller"],
    "destaque": true,
    "novo": false,
    "avaliacao": 4.9,
    "num_avaliacoes": 2847
  },
  {
    "id": 2,
    "nome": "Premier Cru O Creme Rico",
    "categoria": "hidratacao",
    "subcategoria": "Cremes",
    "colecao": "Premier Cru",
    "descricao_curta": "Creme antienvelhecimento de luxo para pele seca e muito seca",
    "descricao_completa": "O creme mais luxuoso da Caudalie, inspirado nos melhores vinhos do mundo. Combina 9 ativos antienvelhecimento para reduzir rugas, restaurar a firmeza e devolver a luminosidade. Textura rica e sensorial que transforma a rotina em um momento de prazer.",
    "imagem": "assets/products/premier-cru-creme.jpg",
    "imagem_placeholder": "premier-cru",
    "preco": 689.00,
    "preco_formatado": "R$ 689,00",
    "parcelamento": "em até 6x de R$ 114,83",
    "beneficios": ["9 ativos antienvelhecimento", "Reduz rugas profundas", "Restaura firmeza e elasticidade", "Efeito lifting visível"],
    "ingredientes": "Resveratrol, Polifenóis da Uva, Ácido Hialurônico, Pré-biótico da Uva, Péptidos de Seda",
    "volume": "50ml",
    "modo_uso": "Aplique pela manhã e/ou à noite sobre a pele limpa do rosto e pescoço com movimentos ascendentes.",
    "tags": ["antienvelhecimento", "creme", "premier cru", "luxo", "firmeza"],
    "destaque": true,
    "novo": false,
    "avaliacao": 4.8,
    "num_avaliacoes": 1523
  },
  {
    "id": 3,
    "nome": "Beauty Elixir Bruma Facial",
    "categoria": "skincare",
    "subcategoria": "Tônicos e Brumas",
    "colecao": "Beauty Elixir",
    "descricao_curta": "A bruma multifuncional que prepara, ilumina e fixa a maquiagem",
    "descricao_completa": "O icônico Beauty Elixir da Caudalie em um novo frasco. Prepara a pele antes da maquiagem, fixa a base e ilumina a qualquer momento do dia. Fórmula com Água de Uva, Menta Orgânica e Rosmaninho. O segredo de beleza das top models e maquiadores.",
    "imagem": "assets/products/beauty-elixir.jpg",
    "imagem_placeholder": "beauty-elixir",
    "preco": 219.00,
    "preco_formatado": "R$ 219,00",
    "parcelamento": "em até 4x de R$ 54,75",
    "beneficios": ["Prepara a pele para maquiagem", "Fixa e prolonga a maquiagem", "Ilumina instantaneamente", "Refresca a qualquer momento"],
    "ingredientes": "Água de Uva Orgânica, Extrato de Rosmaninho, Menta Orgânica, Extrato de Laranjeira",
    "volume": "100ml",
    "modo_uso": "Borrife sobre o rosto limpo antes da maquiagem ou durante o dia para um efeito iluminado e refrescante. Mantenha o frasco a 20cm do rosto.",
    "tags": ["bruma", "maquiagem", "iluminador", "beauty elixir", "bestseller"],
    "destaque": true,
    "novo": false,
    "avaliacao": 4.7,
    "num_avaliacoes": 3291
  },
  {
    "id": 4,
    "nome": "Vinosource Hydra SOS Hidratante",
    "categoria": "hidratacao",
    "subcategoria": "Cremes",
    "colecao": "Vinosource",
    "descricao_curta": "Gel-creme de hidratação intensa para pele desidratada",
    "descricao_completa": "O creme ideal para peles desidratadas e sensíveis. Sua fórmula exclusiva com Água de Uva Orgânica e Resveratrol proporciona 48h de hidratação contínua, reduz a sensação de tensão e fortalece a barreira cutânea. Textura leve e não gordurosa.",
    "imagem": "assets/products/vinosource-hydra.jpg",
    "imagem_placeholder": "vinosource",
    "preco": 289.00,
    "preco_formatado": "R$ 289,00",
    "parcelamento": "em até 6x de R$ 48,17",
    "beneficios": ["48h de hidratação contínua", "Reduz sensação de tensão", "Fortalece a barreira cutânea", "Textura leve"],
    "ingredientes": "Água de Uva Orgânica, Resveratrol, Ácido Hialurônico de Peso Molecular Múltiplo, Extrato de Flores de Açucena",
    "volume": "40ml",
    "modo_uso": "Aplique manhã e noite sobre a pele limpa e tonificada do rosto, pescoço e colo.",
    "tags": ["hidratação", "vinosource", "pele seca", "sensível"],
    "destaque": false,
    "novo": false,
    "avaliacao": 4.6,
    "num_avaliacoes": 876
  },
  {
    "id": 5,
    "nome": "Vinoclean Espuma de Limpeza",
    "categoria": "limpeza",
    "subcategoria": "Limpeza Facial",
    "colecao": "Vinoclean",
    "descricao_curta": "Espuma purificante que limpa profundamente sem ressecar",
    "descricao_completa": "A espuma de limpeza facial que respeita a pele e o planeta. Remove impurezas, maquiagem e excesso de sebo de forma eficaz e suave. Formulada com Uva Branca Orgânica e Polifenóis da Uva, deixa a pele limpa, macia e com pH equilibrado.",
    "imagem": "assets/products/vinoclean-espuma.jpg",
    "imagem_placeholder": "vinoclean",
    "preco": 179.00,
    "preco_formatado": "R$ 179,00",
    "parcelamento": "em até 4x de R$ 44,75",
    "beneficios": ["Limpeza profunda e suave", "Preserva o pH natural", "Remove maquiagem", "Fórmula vegana"],
    "ingredientes": "Uva Branca Orgânica, Polifenóis da Uva, Extrato de Algodão Orgânico, Glicerina Vegetal",
    "volume": "150ml",
    "modo_uso": "Aplique sobre a pele úmida de manhã e à noite. Massageie em movimentos circulares e enxágue com água morna.",
    "tags": ["limpeza", "vinoclean", "espuma", "purificante"],
    "destaque": false,
    "novo": false,
    "avaliacao": 4.5,
    "num_avaliacoes": 1102
  },
  {
    "id": 6,
    "nome": "Resveratrol-Lift Sérum Firmador",
    "categoria": "seruns",
    "subcategoria": "Séruns",
    "colecao": "Resveratrol-Lift",
    "descricao_curta": "Sérum firmador alternativa ao retinol com Resveratrol",
    "descricao_completa": "O sérum firmador mais poderoso da Caudalie. Alternativa eficaz ao retinol, baseada no Resveratrol da Uva — antioxidante 10.000x mais potente que a vitamina E. Reduz visivelmente rugas, restaura a firmeza e promove efeito lifting em 4 semanas.",
    "imagem": "assets/products/resveratrol-lift.jpg",
    "imagem_placeholder": "resveratrol",
    "preco": 419.00,
    "preco_formatado": "R$ 419,00",
    "parcelamento": "em até 6x de R$ 69,83",
    "beneficios": ["Alternativa ao retinol", "Efeito lifting em 4 semanas", "Reduz rugas profundas", "Restaura firmeza"],
    "ingredientes": "Resveratrol da Uva, Peptídeos Vegetais, Ácido Hialurônico, Extrato de Bambu",
    "volume": "30ml",
    "modo_uso": "Aplique 3 a 4 gotas à noite sobre a pele limpa. Para uso diurno, complete com filtro solar.",
    "tags": ["firmeza", "lifting", "resveratrol", "antienvelhecimento", "retinol alternativo"],
    "destaque": true,
    "novo": false,
    "avaliacao": 4.8,
    "num_avaliacoes": 2034
  },
  {
    "id": 7,
    "nome": "Vinotherapist Creme Corporal",
    "categoria": "corpo",
    "subcategoria": "Corpo",
    "colecao": "Vinotherapist",
    "descricao_curta": "Creme corporal de luxo com óleo de semente de uva",
    "descricao_completa": "O creme corporal que transforma o ritual de hidratação em uma experiência spa. Formulado com Óleo de Semente de Uva prensado a frio e Manteiga de Karité, nutre profundamente, restaura a elasticidade e deixa a pele aveludada por 48h.",
    "imagem": "assets/products/vinotherapist-corpo.jpg",
    "imagem_placeholder": "vinotherapist",
    "preco": 249.00,
    "preco_formatado": "R$ 249,00",
    "parcelamento": "em até 4x de R$ 62,25",
    "beneficios": ["Hidratação 48h", "Textura luxuosa e aveludada", "Óleo de semente de uva", "Restaura elasticidade"],
    "ingredientes": "Óleo de Semente de Uva, Manteiga de Karité, Ácido Hialurônico, Extrato de Uva Tinta",
    "volume": "250ml",
    "modo_uso": "Aplique sobre a pele limpa do corpo, preferencialmente após o banho, com movimentos de massagem ascendentes.",
    "tags": ["corpo", "hidratante", "vinotherapist", "luxo"],
    "destaque": false,
    "novo": false,
    "avaliacao": 4.7,
    "num_avaliacoes": 654
  },
  {
    "id": 8,
    "nome": "Thé des Vignes Eau Fraîche",
    "categoria": "fragrancias",
    "subcategoria": "Fragrâncias",
    "colecao": "Thé des Vignes",
    "descricao_curta": "Fragrância leve e fresca com notas de chá branco e flor de laranjeira",
    "descricao_completa": "Uma fragrância floral aquática que evoca a leveza dos jardins de vinha ao entardecer. Notas de topo de chá branco e bergamota, coração de flor de laranjeira e jasmim, fundo de almíscar branco e madeira de cedro. Leve, refrescante e sofisticada.",
    "imagem": "assets/products/the-des-vignes.jpg",
    "imagem_placeholder": "the-des-vignes",
    "preco": 299.00,
    "preco_formatado": "R$ 299,00",
    "parcelamento": "em até 6x de R$ 49,83",
    "beneficios": ["Fragrância floral aquática", "Longa duração", "Frasco elegante", "Sem parabenos"],
    "ingredientes": "Notas de Chá Branco, Flor de Laranjeira, Bergamota, Jasmim, Almíscar Branco",
    "volume": "50ml",
    "modo_uso": "Borrifar sobre os pulsos, pescoço e pontos de pulso. Não aplicar diretamente sobre joias.",
    "tags": ["fragrância", "eau fraîche", "floral", "thé des vignes"],
    "destaque": false,
    "novo": false,
    "avaliacao": 4.6,
    "num_avaliacoes": 432
  },
  {
    "id": 9,
    "nome": "Eau des Vignes Eau Fraîche",
    "categoria": "fragrancias",
    "subcategoria": "Fragrâncias",
    "colecao": "Eau des Vignes",
    "descricao_curta": "Fragrância verde e cítrica inspirada nas vinhas da Borgonha",
    "descricao_completa": "Uma fragrância vibrante e contemporânea que captura a essência dos vinhedos em flor. Notas verdes e cítricas de bergamota e limão siciliano, com coração de folha de violeta e peônia, e fundo de madeira de sândalo e almíscar.",
    "imagem": "assets/products/eau-des-vignes.jpg",
    "imagem_placeholder": "eau-des-vignes",
    "preco": 289.00,
    "preco_formatado": "R$ 289,00",
    "parcelamento": "em até 6x de R$ 48,17",
    "beneficios": ["Fragrância verde e cítrica", "Vibrante e contemporânea", "Longa fixação", "Unissex"],
    "ingredientes": "Bergamota, Limão Siciliano, Folha de Violeta, Peônia, Sândalo, Almíscar",
    "volume": "50ml",
    "modo_uso": "Borrifar sobre os pulsos, pescoço e pontos de calor. Reaplicar conforme desejado.",
    "tags": ["fragrância", "eau fraîche", "cítrico", "eau des vignes"],
    "destaque": false,
    "novo": false,
    "avaliacao": 4.5,
    "num_avaliacoes": 318
  },
  {
    "id": 10,
    "nome": "Soleil des Vignes Eau Fraîche",
    "categoria": "fragrancias",
    "subcategoria": "Fragrâncias",
    "colecao": "Soleil des Vignes",
    "descricao_curta": "Fragrância solar e quente com notas de figos e pêssego",
    "descricao_completa": "Uma fragrância que evoca o calor dourado do sol sobre os vinhedos. Notas de figo e pêssego branco no topo, coração de peônia e magnólia, fundo de baunilha e almíscar quente. Sensual, envolvente e inesquecível.",
    "imagem": "assets/products/soleil-des-vignes.jpg",
    "imagem_placeholder": "soleil-des-vignes",
    "preco": 289.00,
    "preco_formatado": "R$ 289,00",
    "parcelamento": "em até 6x de R$ 48,17",
    "beneficios": ["Fragrância solar e quente", "Longa duração", "Sensual e envolvente", "Frasco colecionável"],
    "ingredientes": "Figo, Pêssego Branco, Peônia, Magnólia, Baunilha, Almíscar",
    "volume": "50ml",
    "modo_uso": "Aplique nos pontos de pulso e pescoço. A fragrância se desenvolve com o calor natural do corpo.",
    "tags": ["fragrância", "eau fraîche", "solar", "soleil des vignes"],
    "destaque": false,
    "novo": true,
    "avaliacao": 4.7,
    "num_avaliacoes": 287
  },
  {
    "id": 11,
    "nome": "Ange des Vignes Eau Fraîche",
    "categoria": "fragrancias",
    "subcategoria": "Fragrâncias",
    "colecao": "Ange des Vignes",
    "descricao_curta": "Fragrância delicada com notas de rosa branca e patchouli",
    "descricao_completa": "Uma fragrância etérea e feminina que captura a pureza das pétalas ao amanhecer. Notas de topo de bergamota e limão, coração de rosa branca e lírio do vale, fundo de patchouli e madeira de cedro. Sofisticada, delicada e memorável.",
    "imagem": "assets/products/ange-des-vignes.jpg",
    "imagem_placeholder": "ange-des-vignes",
    "preco": 289.00,
    "preco_formatado": "R$ 289,00",
    "parcelamento": "em até 6x de R$ 48,17",
    "beneficios": ["Fragrância floral etérea", "Alta fixação", "Feminina e sofisticada", "Sem alérgenos comuns"],
    "ingredientes": "Bergamota, Rosa Branca, Lírio do Vale, Patchouli, Cedro",
    "volume": "50ml",
    "modo_uso": "Borrifar sobre o pescoço, pulsos e decote para um efeito duradouro e envolvente.",
    "tags": ["fragrância", "eau fraîche", "floral", "ange des vignes"],
    "destaque": false,
    "novo": true,
    "avaliacao": 4.6,
    "num_avaliacoes": 203
  },
  {
    "id": 12,
    "nome": "Fleur de Vigne Eau Fraîche",
    "categoria": "fragrancias",
    "subcategoria": "Fragrâncias",
    "colecao": "Fleur de Vigne",
    "descricao_curta": "Fragrância floral e frutal com notas de peônia e pêra",
    "descricao_completa": "Uma fragrância jovem e vibrante que celebra a floração das vinhas na primavera. Notas de pêra e framboesa no topo, coração de peônia e rosa, fundo de almíscar branco e madeira de sândalo. Fresca, moderna e irresistível.",
    "imagem": "assets/products/fleur-de-vigne.jpg",
    "imagem_placeholder": "fleur-de-vigne",
    "preco": 269.00,
    "preco_formatado": "R$ 269,00",
    "parcelamento": "em até 6x de R$ 44,83",
    "beneficios": ["Fragrância floral e frutal", "Jovem e vibrante", "Versátil e moderna", "Frasco elegante"],
    "ingredientes": "Pêra, Framboesa, Peônia, Rosa, Almíscar Branco, Sândalo",
    "volume": "50ml",
    "modo_uso": "Borrifar generosamente sobre o corpo e roupas para um envolvimento fragrante duradouro.",
    "tags": ["fragrância", "eau fraîche", "frutal", "fleur de vigne"],
    "destaque": false,
    "novo": false,
    "avaliacao": 4.5,
    "num_avaliacoes": 178
  }
]
